### ISSUE TITLE
Cancel & Done buttons not dismissing the contacts list

### ISSUE THREAD

**Issue by rayjas** [JettF/JFContactsPicker#7]
Hi! Once I select the contacts and click on done, I don't go back to the original controllers. I believe the onTouchCancelButton and onTouchDoneButton in ContactsPicker.swift need to include a dismiss statement. Would you be able to add this to the project? Many thanks and keep up the good work!

**Comment by danishnaeem57** [comment]
for cancel button, use delegate function contactPicker(_: ContactsPicker, didCancel error: NSError).

**Comment by JettF** [comment]
My apologies for taking so long to get back to you. @danishnaeem57 is correct. You can implement the delegate functions and call the `dismiss()` in your implementation. I set it up this way so it's more open to customization. For example if you want to display an alert before dismissing the ContactsPicker you can do so in the delegate methods.

**Comment by JettF** [comment]
I am going to close this issue. Feel free to open it again if you have further questions!
