### ISSUE TITLE
Done button on multiple select does not trigger delegate method didSelectMultipleContacts

### ISSUE THREAD

**Issue by dmachacon** [JettF/JFContactsPicker#8]
The Cancel button is able to trigger the didCancel delegate method, however, the Done button doesn't trigger it's delegate method.

**Comment by JettF** [comment]
Thanks for letting me know! I'll update the example project.

**Comment by WentaoHu** [comment]
@JettF I just test it, I think this issue can be closed
`func contactPicker(_: ContactsPicker, didSelectMultipleContacts contacts: [Contact])` will be triggered correctly. 

meanwhile
`func contactPicker(_: ContactsPicker, didSelectContact contact: Contact)` is not triggered as desired

**Comment by JettF** [comment]
Thanks for checking @WentaoHu. I'll close this.
